vich_uploader:
    db_driver: orm

    mappings:
      publication_images:
            uri_prefix: '%publication_images%'
            upload_destination: '%kernel.project_dir%/public%publication_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
      projets_images:
            uri_prefix: '%projets_images%'
            upload_destination: '%kernel.project_dir%/public%projets_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 
